services:
  brain-tumor-api:
    build:
      context: .
    image:
      brain-tumor-api:latest
    container_name:
      brain-tumor-api
    restart:
      unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
    environment:
      MODEL_VERSION:
        resnet18-accuracy=97.78-F1=98.01
      MODEL_DIR:
        /app/artifacts
      PYTHONUNBUFFERED: 1
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/health"
        ]
      interval:
        30s
      timeout:
        5s
      retries:
        3
    deploy:
      resources:
        limits:
          memory:
            4G